-- Demo catalogue: one product per category, for checking the site end to end
-- before real data exists. Agriculture is the real range; the industrial and
-- home automation rows exist so those two markets are not empty shells while
-- their product lists are still being written.
--
-- Run it on the server (the database has no host port, so it goes through the
-- container):
--
--   docker compose exec -T db psql -v ON_ERROR_STOP=1 -U vkon -d vkon < scripts/seed-demo.sql
--
-- Locally, against the dev Postgres:
--
--   docker exec -i vkon-pg psql -v ON_ERROR_STOP=1 -U postgres -d vkon < scripts/seed-demo.sql
--
-- Everything here is placeholder: the images are line drawings generated by
-- scripts/make-placeholder-images.py and the copy is plausible rather than
-- accurate. Every name starts with "DEMO" so it is obvious in the admin what
-- is real and what is not. Re-running updates the same rows rather than
-- creating duplicates; delete them from /admin once you have real products.

INSERT INTO products (
  id, slug, name, category, tagline, description,
  hp_ranges, features, protections, spec, images,
  video_url, video_title, published, featured, sort_order
) VALUES
(
  gen_random_uuid(), 'demo-dol-starter', 'DEMO DOL Starter Panel', 'starter',
  'Direct-on-line starting for small pumps, with the full protection set',
  E'DEMO PRODUCT — placeholder copy and drawn artwork.\n\nDirect-on-line starting for three phase pumps between 3 and 10 HP. Current and voltage are read on all three phases continuously and shown on the front panel, so a fault is a number rather than a guess.\n\nProtection covers what actually destroys pumps on a rural feeder: the borewell running dry, a phase dropping out, supply outside the safe band, and a reversed phase sequence after line work.',
  ARRAY['3 – 7.5 HP','10 HP'],
  ARRAY['Three phase amps and voltage on the display','Instantaneous fault display naming the last trip','Auto start with adjustable power-on timer','Dry run protection with automatic restart'],
  ARRAY['dry-run','single-phase','hv-lv','phase-reversal','overload-relay','voltage-current-sensing'],
  '[{"label":"Type","value":"Direct on line (DOL)"},{"label":"Motor range","value":"3 – 10 HP"},{"label":"Supply","value":"3 phase"},{"label":"Warranty","value":"PLACEHOLDER"}]'::jsonb,
  '[{"url":"/products/demo-starter.jpg","alt":"DEMO DOL starter panel, front view"},{"url":"/products/demo-terminals.jpg","alt":"Terminal block detail"}]'::jsonb,
  NULL, NULL, true, true, 1
),
(
  gen_random_uuid(), 'demo-solar-controller', 'DEMO Solar Pump Controller', 'solar',
  'Runs the pump on solar, on mains, or changes over between them',
  E'DEMO PRODUCT — placeholder copy and drawn artwork.\n\nA controller that drives the pump from a solar array, from mains, or changes over between the two as the day allows. The protection set watches the motor whichever source is driving it.',
  ARRAY['3 HP','5 HP'],
  ARRAY['Automatic changeover between solar and mains','Dry run protection','Overload and voltage monitoring'],
  ARRAY['solar-powered','dry-run','overload-relay','hv-lv'],
  '[{"label":"Type","value":"Solar / mains changeover"},{"label":"Motor range","value":"3 – 5 HP"},{"label":"Warranty","value":"PLACEHOLDER"}]'::jsonb,
  '[{"url":"/products/demo-solar.jpg","alt":"DEMO solar pump controller, front view"}]'::jsonb,
  NULL, NULL, true, false, 1
),
(
  gen_random_uuid(), 'demo-auto-start-timer', 'DEMO Auto Start Timer', 'auto-start',
  'Adds automatic starting to a starter you already own',
  E'DEMO PRODUCT — placeholder copy and drawn artwork.\n\nBrings the pump back when three phase supply returns within safe limits, after an adjustable delay so it never starts into an unstable line. A cyclic timer runs it on a repeating schedule through the night.',
  ARRAY['Up to 10 HP'],
  ARRAY['Adjustable restart delay','Separate on and off cycle timers','Works with an existing starter'],
  ARRAY['auto-start-timer','cyclic-timer','hv-lv'],
  '[{"label":"Type","value":"Auto start / cyclic timer"},{"label":"Warranty","value":"PLACEHOLDER"}]'::jsonb,
  '[{"url":"/products/demo-auto-start.jpg","alt":"DEMO auto start timer, front view"}]'::jsonb,
  NULL, NULL, true, false, 1
),
(
  gen_random_uuid(), 'demo-submersible-cable', 'DEMO Submersible Cable', 'cable',
  'Flat submersible cable for continuous underwater duty',
  E'DEMO PRODUCT — placeholder copy and drawn artwork.\n\nSubmersible cable for continuous underwater duty, where ordinary wiring gives way at the joint long before the conductor does. Sized to the panel and the motor it will run.',
  ARRAY['3 core'],
  ARRAY['Continuous underwater duty','Sized to the panel and motor'],
  ARRAY[]::text[],
  '[{"label":"Type","value":"Flat submersible"},{"label":"Cores","value":"3"},{"label":"Warranty","value":"PLACEHOLDER"}]'::jsonb,
  '[{"url":"/products/demo-cable.jpg","alt":"DEMO submersible cable coil"}]'::jsonb,
  NULL, NULL, true, false, 1
),
(
  gen_random_uuid(), 'demo-gsm-mobile-control', 'DEMO GSM Mobile Control', 'accessory',
  'Switch the motor on or off from any phone, by call or SMS',
  E'DEMO PRODUCT — placeholder copy and drawn artwork.\n\nSwitches the motor from any phone by call or SMS and sends status back as a message. Fits alongside an existing panel.',
  ARRAY['Any HP'],
  ARRAY['Call or SMS control','Status reply by message','Fits an existing panel'],
  ARRAY['mobile-control'],
  '[{"label":"Type","value":"GSM remote control"},{"label":"Warranty","value":"PLACEHOLDER"}]'::jsonb,
  '[{"url":"/products/demo-accessory.jpg","alt":"DEMO GSM mobile control unit"}]'::jsonb,
  NULL, NULL, true, false, 1
),

-- Industrial. One row so the Industrial market has something behind it.
(
  gen_random_uuid(), 'demo-industrial-dol', 'DEMO Industrial DOL Panel', 'industrial-panel',
  'Direct-on-line motor control for continuous industrial duty',
  E'DEMO PRODUCT — placeholder copy and drawn artwork.\n\nMotor control and protection for industrial duty, where the load runs continuously and a stopped machine costs more in an afternoon than the panel driving it. Same protection set as the agricultural range, in the ratings and enclosure a shop floor asks for.',
  ARRAY['15 HP','25 HP'],
  ARRAY['Three phase amps and voltage on the display','Overload and single phasing protection','Sheet steel enclosure'],
  ARRAY['single-phase','hv-lv','phase-reversal','overload-relay','voltage-current-sensing'],
  '[{"label":"Type","value":"Direct on line (DOL)"},{"label":"Motor range","value":"15 – 25 HP"},{"label":"Supply","value":"3 phase"},{"label":"Warranty","value":"PLACEHOLDER"}]'::jsonb,
  '[{"url":"/products/demo-industrial.jpg","alt":"DEMO industrial DOL panel, front view"}]'::jsonb,
  NULL, NULL, true, false, 1
),

-- Commercial / home automation. The two the client named.
-- No hp_ranges and no protections: both taxonomies are about motors, and
-- padding these rows with either would put a lighting module in the pump
-- rating filter.
(
  gen_random_uuid(), 'demo-wardrobe-auto-light', 'DEMO Wardrobe Auto Light', 'home-automation',
  'Lights the wardrobe when the door opens, and goes dark when it shuts',
  E'DEMO PRODUCT — placeholder copy and drawn artwork.\n\nA sensor and strip that light the inside of a wardrobe as the door opens and switch off behind it. No switch to find in the dark, and nothing left burning because somebody forgot.',
  ARRAY[]::text[],
  ARRAY['Door sensor, no switch to operate','Adjustable off delay','Warm white strip'],
  ARRAY[]::text[],
  '[{"label":"Type","value":"Door-sensed lighting module"},{"label":"Supply","value":"PLACEHOLDER"},{"label":"Warranty","value":"PLACEHOLDER"}]'::jsonb,
  '[{"url":"/products/demo-wardrobe-light.jpg","alt":"DEMO wardrobe auto light module and strip"}]'::jsonb,
  NULL, NULL, true, true, 1
),
(
  gen_random_uuid(), 'demo-staircase-auto-light', 'DEMO Staircase Auto Light', 'home-automation',
  'Lights the stairs as you reach them and turns off behind you',
  E'DEMO PRODUCT — placeholder copy and drawn artwork.\n\nMotion-sensed lighting for a staircase or passage. It lights the flight as you reach it, holds while there is movement, and goes off after an adjustable delay once the stairs are clear.',
  ARRAY[]::text[],
  ARRAY['Motion sensed, both directions','Adjustable hold time','Daylight cut-off so it stays off by day'],
  ARRAY[]::text[],
  '[{"label":"Type","value":"Motion-sensed lighting module"},{"label":"Supply","value":"PLACEHOLDER"},{"label":"Warranty","value":"PLACEHOLDER"}]'::jsonb,
  '[{"url":"/products/demo-staircase-light.jpg","alt":"DEMO staircase auto light module and strip"}]'::jsonb,
  NULL, NULL, true, false, 2
),
(
  gen_random_uuid(), 'demo-kitchen-undercabinet-light', 'DEMO Kitchen Under-Cabinet Light', 'home-automation',
  'Lights the counter when a hand crosses the sensor beneath the cabinet',
  E'DEMO PRODUCT — placeholder copy and drawn artwork.\n\nA warm-white strip mounted under a kitchen cabinet, switched by a wave sensor rather than a wall switch — hands full of vegetables need not stop to look. Adjustable timeout and daylight cut-off.',
  ARRAY[]::text[],
  ARRAY['Wave-sensed, no touch required','Adjustable off delay','Daylight cut-off so it stays off by day'],
  ARRAY[]::text[],
  '[{"label":"Type","value":"Wave-sensed lighting module"},{"label":"Supply","value":"PLACEHOLDER"},{"label":"Warranty","value":"PLACEHOLDER"}]'::jsonb,
  '[{"url":"/products/demo-wardrobe-light.jpg","alt":"DEMO kitchen under-cabinet light module and strip"}]'::jsonb,
  NULL, NULL, true, false, 3
)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  category = EXCLUDED.category,
  tagline = EXCLUDED.tagline,
  description = EXCLUDED.description,
  hp_ranges = EXCLUDED.hp_ranges,
  features = EXCLUDED.features,
  protections = EXCLUDED.protections,
  spec = EXCLUDED.spec,
  images = EXCLUDED.images,
  published = EXCLUDED.published,
  featured = EXCLUDED.featured,
  sort_order = EXCLUDED.sort_order,
  updated_at = now();
