-- Demo catalogue: one product per category, for checking the site end to end
-- before real data exists.
--
-- Run it on the server (the database has no host port, so it goes through the
-- container):
--
--   docker compose exec -T db psql -v ON_ERROR_STOP=1 -U vkon -d vkon < scripts/seed-demo.sql
--
-- Locally, against the dev Postgres:
--
--   docker exec -i vkon-pg psql -v ON_ERROR_STOP=1 -U postgres -d vkon < scripts/seed-demo.sql
--
-- Everything here is placeholder: the images are line drawings generated by
-- scripts/make-placeholder-images.py and the copy is plausible rather than
-- accurate. Every name starts with "DEMO" so it is obvious in the admin what
-- is real and what is not. Re-running updates the same rows rather than
-- creating duplicates; delete them from /admin once you have real products.

INSERT INTO products (
  id, slug, name, category, tagline, description,
  hp_ranges, features, protections, spec, images,
  video_url, video_title, published, featured, sort_order
) VALUES
(
  gen_random_uuid(), 'demo-dol-starter', 'DEMO DOL Starter Panel', 'starter',
  'Direct-on-line starting for small pumps, with the full protection set',
  E'DEMO PRODUCT — placeholder copy and drawn artwork.\n\nDirect-on-line starting for three phase pumps between 3 and 10 HP. Current and voltage are read on all three phases continuously and shown on the front panel, so a fault is a number rather than a guess.\n\nProtection covers what actually destroys pumps on a rural feeder: the borewell running dry, a phase dropping out, supply outside the safe band, and a reversed phase sequence after line work.',
  ARRAY['3 – 7.5 HP','10 HP'],
  ARRAY['Three phase amps and voltage on the display','Instantaneous fault display naming the last trip','Auto start with adjustable power-on timer','Dry run protection with automatic restart'],
  ARRAY['dry-run','single-phase','hv-lv','phase-reversal','overload-relay','voltage-current-sensing'],
  '[{"label":"Type","value":"Direct on line (DOL)"},{"label":"Motor range","value":"3 – 10 HP"},{"label":"Supply","value":"3 phase"},{"label":"Warranty","value":"PLACEHOLDER"}]'::jsonb,
  '[{"url":"/products/demo-starter.jpg","alt":"DEMO DOL starter panel, front view"},{"url":"/products/demo-terminals.jpg","alt":"Terminal block detail"}]'::jsonb,
  NULL, NULL, true, true, 1
),
(
  gen_random_uuid(), 'demo-solar-controller', 'DEMO Solar Pump Controller', 'solar',
  'Runs the pump on solar, on mains, or changes over between them',
  E'DEMO PRODUCT — placeholder copy and drawn artwork.\n\nA controller that drives the pump from a solar array, from mains, or changes over between the two as the day allows. The protection set watches the motor whichever source is driving it.',
  ARRAY['3 HP','5 HP'],
  ARRAY['Automatic changeover between solar and mains','Dry run protection','Overload and voltage monitoring'],
  ARRAY['solar-powered','dry-run','overload-relay','hv-lv'],
  '[{"label":"Type","value":"Solar / mains changeover"},{"label":"Motor range","value":"3 – 5 HP"},{"label":"Warranty","value":"PLACEHOLDER"}]'::jsonb,
  '[{"url":"/products/demo-solar.jpg","alt":"DEMO solar pump controller, front view"}]'::jsonb,
  NULL, NULL, true, false, 1
),
(
  gen_random_uuid(), 'demo-auto-start-timer', 'DEMO Auto Start Timer', 'auto-start',
  'Adds automatic starting to a starter you already own',
  E'DEMO PRODUCT — placeholder copy and drawn artwork.\n\nBrings the pump back when three phase supply returns within safe limits, after an adjustable delay so it never starts into an unstable line. A cyclic timer runs it on a repeating schedule through the night.',
  ARRAY['Up to 10 HP'],
  ARRAY['Adjustable restart delay','Separate on and off cycle timers','Works with an existing starter'],
  ARRAY['auto-start-timer','cyclic-timer','hv-lv'],
  '[{"label":"Type","value":"Auto start / cyclic timer"},{"label":"Warranty","value":"PLACEHOLDER"}]'::jsonb,
  '[{"url":"/products/demo-auto-start.jpg","alt":"DEMO auto start timer, front view"}]'::jsonb,
  NULL, NULL, true, false, 1
),
(
  gen_random_uuid(), 'demo-submersible-cable', 'DEMO Submersible Cable', 'cable',
  'Flat submersible cable for continuous underwater duty',
  E'DEMO PRODUCT — placeholder copy and drawn artwork.\n\nSubmersible cable for continuous underwater duty, where ordinary wiring gives way at the joint long before the conductor does. Sized to the panel and the motor it will run.',
  ARRAY['3 core'],
  ARRAY['Continuous underwater duty','Sized to the panel and motor'],
  ARRAY[]::text[],
  '[{"label":"Type","value":"Flat submersible"},{"label":"Cores","value":"3"},{"label":"Warranty","value":"PLACEHOLDER"}]'::jsonb,
  '[{"url":"/products/demo-cable.jpg","alt":"DEMO submersible cable coil"}]'::jsonb,
  NULL, NULL, true, false, 1
),
(
  gen_random_uuid(), 'demo-gsm-mobile-control', 'DEMO GSM Mobile Control', 'accessory',
  'Switch the motor on or off from any phone, by call or SMS',
  E'DEMO PRODUCT — placeholder copy and drawn artwork.\n\nSwitches the motor from any phone by call or SMS and sends status back as a message. Fits alongside an existing panel.',
  ARRAY['Any rating'],
  ARRAY['Call or SMS control','Status reply by message','Fits an existing panel'],
  ARRAY['mobile-control'],
  '[{"label":"Type","value":"GSM remote control"},{"label":"Warranty","value":"PLACEHOLDER"}]'::jsonb,
  '[{"url":"/products/demo-accessory.jpg","alt":"DEMO GSM mobile control unit"}]'::jsonb,
  NULL, NULL, true, false, 1
)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  category = EXCLUDED.category,
  tagline = EXCLUDED.tagline,
  description = EXCLUDED.description,
  hp_ranges = EXCLUDED.hp_ranges,
  features = EXCLUDED.features,
  protections = EXCLUDED.protections,
  spec = EXCLUDED.spec,
  images = EXCLUDED.images,
  published = EXCLUDED.published,
  featured = EXCLUDED.featured,
  sort_order = EXCLUDED.sort_order,
  updated_at = now();
